### ISSUE TITLE
Real world examples? Some questions to Infinitic 

### ISSUE THREAD

**Issue by Skyleiger** [infiniticio/infinitic#226]
Good morning.

First of all, a big compliment to your project. I came across Infinitic through a post on Medium.com and it is exactly the library or framework that I was missing for the development of distributed event-based systems.

In fact, I was initially interested in Nakadi from Zalando, but its development is no longer openly continued. Infinitic now relieves me of the work of taking care of such a system myself.

I think the choice of the Kotlin programming language is a good one and I see myself possibly supporting the development of this project a little in the future.

First, however, I would like to see Infinitic in action and this raises a few questions for me. Although you have provided several examples in your detailed documentation, I still miss the real-world examples.

So, I have the following questions:

1. are there already some projects that use Infinitic productively?

2. what should Infinitic best be used for? Only long-running tasks, or can it also be used, for example, to distribute HTTP requests via the infrastructure? (e.g. as a kind of load balancing)

3. in my use case, for example, I would like to use workflows to perform periodic ping checks on defined servers. The interval of the check can be different for each server. Can this be covered with Infinitic? Do you make one workflow for all servers, or one workflow per server?

4. what should the system distribution look like? There are the workflow workers and the service workers. Does each workflow worker know all the workflows, or are they split up? (e.g. one worker for order workflows, one worker for payment workflows, etc.)? I ask myself the same question for the services? And then I would also need the applications that provide the (HTTP) API of my application and call the workflows via an Infinitic client, right?

I know that's a lot of questions. I would be very grateful if we could talk a little. It would certainly add value to the overall project.

**Comment by geomagilles** [comment]
Hi, and thank you for your comment. I'm glad to hear that you find Infinitic useful. I appreciate your interest in contributing to the project in the future. Regarding your questions, I would like to clarify a few points and provide some additional context:

1) Yes, there are already several projects using Infinitic in production environments for more than 2 years now. While we don't have a dedicated website showcasing use cases yet, we are working on creating one to highlight real-world examples and success stories.

2) Infinitic can be used for both long-running tasks and distributing HTTP requests across the infrastructure (see [here](https://medium.com/@gillesbarbier/an-easy-path-from-api-based-microservices-to-an-event-driven-architecture-for-improved-reliability-00d7d0bc3828)). However, due to the latency introduced by state management, Infinitic is not recommended for user-facing requests, except for those where users are waiting for the completion of long-running tasks (let's say > 100ms).

3) Your use case of performing periodic ping checks on defined servers with varying intervals sounds like a good fit for Infinitic. You could create a separate workflow instance for each server, allowing you to define the check interval independently for each one. This approach would typically provide better isolation.

4) Regarding system distribution, Infinitic allows for flexible configuration. Workers can be configured as Service workers, Workflow workers, or both, managing one or more Services or Workflows types. In a production environment, it is generally recommended to have separate worker types (with multiple instances) for each Service and Workflow. This separation helps with individual scaling and isolating potential issues, such as memory leaks. For the applications that initiate workflows, you would indeed need to include an Infinitic client to interact with the system.

I hope these clarifications help address your questions. Please feel free to use the discussion tab if you have any further inquiries or need more detailed explanations. The discussion tab can be particularly helpful for future users who may have similar questions.

**Comment by Skyleiger** [comment]
> Hi, and thank you for your comment. I'm glad to hear that you find Infinitic useful. I appreciate your interest in contributing to the project in the future. Regarding your questions, I would like to clarify a few points and provide some additional context:
> 
> 1. Yes, there are already several projects using Infinitic in production environments for more than 2 years now. While we don't have a dedicated website showcasing use cases yet, we are working on creating one to highlight real-world examples and success stories.
> 2. Infinitic can be used for both long-running tasks and distributing HTTP requests across the infrastructure (see [here](https://medium.com/@gillesbarbier/an-easy-path-from-api-based-microservices-to-an-event-driven-architecture-for-improved-reliability-00d7d0bc3828)). However, due to the latency introduced by state management, Infinitic is not recommended for user-facing requests, except for those where users are waiting for the completion of long-running tasks (let's say > 100ms).
> 3. Your use case of performing periodic ping checks on defined servers with varying intervals sounds like a good fit for Infinitic. You could create a separate workflow instance for each server, allowing you to define the check interval independently for each one. This approach would typically provide better isolation.
> 4. Regarding system distribution, Infinitic allows for flexible configuration. Workers can be configured as Service workers, Workflow workers, or both, managing one or more Services or Workflows types. In a production environment, it is generally recommended to have separate worker types (with multiple instances) for each Service and Workflow. This separation helps with individual scaling and isolating potential issues, such as memory leaks. For the applications that initiate workflows, you would indeed need to include an Infinitic client to interact with the system.
> 
> I hope these clarifications help address your questions. Please feel free to use the discussion tab if you have any further inquiries or need more detailed explanations. The discussion tab can be particularly helpful for future users who may have similar questions.

Thanks for the detailed answer. I actually didn't know about the discussion tab before and therefore overlooked it.
I will refer to it for future questions (which are not issues).
