### ISSUE TITLE
JsonView Support

### ISSUE THREAD

**Issue by nseb** [infiniticio/infinitic#245]
In Jackson, there is a JsonView feature, to have a different json format for the same object. In the case of infinitic, to integrate into an existing project, it would be interesting to support this functionality:
https://www.baeldung.com/jackson-json-view-annotation

For example : 
In workflow , in meta a special meta name , **json.view** , can be set for select the correct json view desired , And Infinitic , if detected this special meta name , set the correct jsonview in the objectmapper.

**Comment by geomagilles** [comment]
I have some comments:

* I feel that it is adapted to serialization in only one direction; with Infinitic, we serialize/deserialize. But I guess there must be properties that can sometimes be ignored in both directions.

* Unless I am mistaken, you don't need new developments if you can update the ObjectMapper globally at worker level. Is that right?

* What would be a new development? The presence of a @JsonView annotation on the objects to be serialized is not enough because I don’t know in advance if the user wants to use it. If I take inspiration from Spring, could Infinitic take into account a @JsonView annotation associated with the implementation of the workflow and the service?

**Comment by nseb** [comment]
Hello @geomagilles 

1. Yes it's correct for serializer/deserialize

2 cf point 3 ,global for jsonview it's not the solution

3  Exact , Therefore for enable a jsonview , for example the client set in the meta map in the init workflow , a special attribute to set the correct jsonview value . As we would do with an annotation in spring at the controller level.
And Infinitic can use this special meta attribute to enable or disable the correct view for serialize/deserialize

**Comment by geomagilles** [comment]
Fixed by b52c8a40bc9b9e3d68b38d1ee29b67bf6fa157cd
